### ISSUE TITLE
As a customer, I would like to know which environments are supported by this company (Windows, network devices, UNIX, etc)

### ISSUE THREAD

**Issue by ozyx** [tigerjpg/cybersecurity#14]
There needs to be a clear list of supported platforms.
This should be visible from a page that displays information about the products offered.

**Comment by theozornelas** [comment]
Enviroments Supported:

Linux 32,64,86 bit versions

	Ubuntu
	Debian
	Mint
	Fedora
	CentOs/Red Hat Enterprise Linux
	openSUSE/SUSE Linux Enterprise
	Mageia/Mandriva
	Arch Linux
	Slackware Linux


Others:
	NONE

Hardware (Minimum):
	Intel® Xeon®
	500 TB of Memory

**Comment by theozornelas** [comment]
Enviroments Supported:

Linux 32,64,86 bit versions

	Ubuntu
	Debian
	Mint
	Fedora
	CentOs/Red Hat Enterprise Linux
	openSUSE/SUSE Linux Enterprise
	Mageia/Mandriva
	Arch Linux
	Slackware Linux


Others:
	NONE

Hardware (Minimum):
	Intel® Xeon®
	500 TB of Memory

**Comment by AnthonyKoutroulis** [comment]
Nice job oz!! I'll add these to the wiki,
also hahaha we support every linux distro, but no windows
