### ISSUE TITLE
As a customer, I want to be able to view testimonials of other customers

### ISSUE THREAD

**Issue by AnthonyKoutroulis** [tigerjpg/cybersecurity#20]

**Comment by theozornelas** [comment]
Company Name: Bimbo
Location:     Tijuana, Baja California, Mexico
Address:       Parque Industrial Pacifico III, Sánchez Taboada

	El producto de seguridad de la compañia Tiger ha sido una pieza clave en el funcionamiento de la empresa. Gracias a su software " Threat Protection ", hemos sido capaces de detectar ataques de otras compañias tales como Wonder Bread, Hostness, Panera, y muchas otras mas. El reporte de ataques es lo que  permite a nuestro equipo de especialistas contratacar los ciberataques. Contamos con la seguridad que nuestros datos estan a salvo sin sacrificar la efectividad del sistema. No estariamos en la sima si no fuera por el sistema de seguridad de Tiger.

**Comment by theozornelas** [comment]
Company Name: H3H3 Productions
Location:     New York, United States of America
Adress:       Confidential

	Tiger has been an extremely vital part of our company. Without their threat detection software, Insider Threat, Fullscreen could have access to our accounts and destroy our show and our hopes for a career in YouTube. The software helped us find that Papa was trying to infiltrate in our webpage in order to expand his orders of
sodi-pops. Tiger replaced our server when the Memory Integrity system deallocated malware in order to ensure a better functionality of the company, and non of the data was lost. We are strongly recommending the company, even our friend Franku is thinking about aquiring the services.

**Comment by theozornelas** [comment]
Company Name: Apple Inc.
Location:     Cupertino, California, United States.
Adress:       1 Infinite Loop

	The software aquired from the company Tiger has been the reson the comany is still afloat. Threat Porotection and Insider threat  have prevented hackers from other companies to reach into our secret developments and has given us the data we need to
counter attack those threats for good. Thanks to the Memory Integrity software we could detect malware in one of our servers, which could end in a data leak in the system. We highly appreciate Tiger and we strongly reccomend to hire such reliable and affortable company.

**Comment by theozornelas** [comment]
Company Name: China National Offshore Oil Corporation
Location:     Beijing, China
Adress:       No.25 Chaoyangmenbei Dajie, Dongcheng District

	Tiger software is a key part of our bussiness. It keeps tabs on our data traffic and it has detected  multiple threats from Japan and United States. Tiger has shown alot of integrity and dicipline when it comes to solutions. It took them 20 minutes to come and fix a problem in the system at 2 a.m; they fixed the issue in under an hour and leaving the system even more efficient than before.Tiger has our respect and loyalty for years to come.

**Comment by theozornelas** [comment]
Company Name: United States Department of Defense
Location:     Wasington D.C, United States
Adress:       1400 Defense Pentagon

	All Tiger products have had a key factor in the protection of this beautiful country. America is safe from the cyber attacks from North Korea, Iran, Russia, and China thanks to Tiger. The company has given us all the  software upgrades required to fight all the new threats being created everyday by the enemies of freedom. Tiger has shown it's reliance when it gives us a report of attacks and routes everyday, regardless of the millions of attacks occurring at the same time. Tiger has our seal of approval and we are proud to call it an American Company. God Bless America.
