### ISSUE TITLE
As a prospective customer, I would like a guarantee policy from this company.

### ISSUE THREAD

**Issue by ozyx** [tigerjpg/cybersecurity#4]

**Comment by theozornelas** [comment]
Tiger Inc. Terms Policy

	The next policy is in accordance with U.S and international 
laws. We do not negociate any of the following terms. Our company
has the professionalism neessary to compensate in case that any 
of our products causes severe damage to the data in a company. In
suxh case, the compensations necessary will be made. 

We are not responsible for any damage done to an individual
done to a user (Excluding Mental). 

In case the software casuses damage to the company system
an investigation will be conducted to coroborate the cause 
of the damage.

There is a 3 time limit corresponding to technical support visits
in a single day.

There are no reinburnsments for technical services provided. No exeptions

Any hardware that w replace has a 1 year warranty with Tiger. If there is
demage to that hardware it will be reaplce without cost
for up to 2 replacements.

Tiger will not share or use any data that is being protected in the system. In case
of a leak by our software, we will provide full compensention and termination
of the contract without any fees or charges.

In case of Bankrupsy, the company will compensate for the remianing of the contract.
