### ISSUE TITLE
As a company that has been called out by a "big cat" expert, we need to come up with the meaning behind the acronym T.I.G.E.R.

### ISSUE THREAD

**Issue by AnthonyKoutroulis** [tigerjpg/cybersecurity#66]
It should involve tigers.
And be awesome.

**Comment by TheSlat** [comment]
Technical Integrity in General Environments by Roaring - TheOz

**Comment by TheSlat** [comment]
Technological Integration Group Emergency Ready

**Comment by AnthonyKoutroulis** [comment]
This Is Good Enough Relax

**Comment by AnthonyKoutroulis** [comment]
This Is Great Everybody Relax
JERRY APPROVED AND CLOSED
